name: Fetch Daily XKCD Comic

on:
  schedule:
    - cron: '0 5 * * *'  # Run daily at 5:00 AM UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Fetch XKCD comic info
      id: fetch-info
      run: |
        INFO=$(curl -s https://xkcd.com/info.0.json)
        IMAGE_URL=$(echo $INFO | jq -r '.img')
        COMIC_NUM=$(echo $INFO | jq -r '.num')
        echo "IMAGE_URL=$IMAGE_URL" >> $GITHUB_OUTPUT
        echo "COMIC_NUM=$COMIC_NUM" >> $GITHUB_OUTPUT

    - name: Download comic
      run: |
        mkdir -p .github/xkcd
        wget -O .github/xkcd/XKCD_daily.png ${{ steps.fetch-info.outputs.IMAGE_URL }}

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .github/xkcd/XKCD_daily.png
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update XKCD comic to #${{ steps.fetch-info.outputs.COMIC_NUM }}" && git push)
