name: Update README with XKCD Alt Text

on:
  workflow_call:
    inputs:
      alt_text:
        required: true
        type: string

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Update README
      run: |
        echo "Updating README.md with the latest XKCD alt text..."
        ALT_TEXT="${{ inputs.alt_text }}"
        echo "ALT_TEXT is: $ALT_TEXT"
        
        # Use perl for more reliable text replacement
        perl -i -pe '
          BEGIN { $alt_text = $ENV{ALT_TEXT}; }
          s/(\*<!-- XKCD_ALT_TEXT_START -->).*?(<!-- XKCD_ALT_TEXT_END -->\*)/defined $alt_text ? "$1$alt_text$2" : $&/e;
        ' README.md
        
        echo "Content of README.md after update:"
        cat README.md
      env:
        ALT_TEXT: ${{ inputs.alt_text }}

    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code README.md || echo "changes=true" >> $GITHUB_OUTPUT

    - name: Commit and push if changed
      if: steps.git-check.outputs.changes == 'true'
      run: |
        echo "Changes detected. Committing and pushing..."
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update README with latest XKCD alt text"
        git pull --rebase origin main
        git push
      
    - name: No changes
      if: steps.git-check.outputs.changes != 'true'
      run: echo "No changes to README.md. Skipping commit."

    - name: Check for errors
      if: failure()
      run: |
        echo "Error occurred. Printing git status and last few commits..."
        git status
        git log -n 5
        exit 1
